Feature/models
gamedoora/gamedoora-model pull request #27
Opened 2023-06-07 08:39 UTC by picksitquick

## Proposed Changes
Requesting @aprajshekhar to review the changes.
- added new models using the DB tables form gamedoora-data/gamedoora-beta-structure.sql.
- these models are subjected to certain changes as we move forward
- the task to make it's DTOs is underway, will be completed within this week itself.
- We can setup calls to discuss on how to finalize these models, atleast for tasks assigned to students.
- Please take your time in reviewing them as we don't want to miss out on any details.
- Thank you, please provide any feedback necessary.

2023-06-10 12:28 UTC, aprajshekhar commented on src/main/java/com/gamedoora/model/db/SchemaMigration.java
> +package com.gamedoora.model.db;
This model can be deleted.

2023-06-10 12:31 UTC, aprajshekhar requested changes
Overall LGTM. Just a few observations.

2023-06-10 12:47 UTC, aprajshekhar requested changes

2023-06-10 12:47 UTC, aprajshekhar commented on src/main/java/com/gamedoora/model/db/Identities.java
> +package com.gamedoora.model.db;
Identities is not required

2023-06-11 05:00 UTC, aprajshekhar requested changes
Thanks for the PR. I have added some observations.
Two more suggestion for mappers 
- Explicitly specify `componentModel = "spring"`  for ```@Mapper` annotation`
- Add `@Builder`  for all the POJOs.
Once these are completed, this PR can be merged.

2023-06-12 10:26 UTC, aprajshekhar approved these changes
Thanks for the changes. LGTM. Approved.

2023-06-12 19:46 UTC, picksitquick commented
I request to pause the merge, @Builder annotation is still creating conflicts, working on it, will be fixed by tomorrow.
Every other changes have been made. creating a repo feature/Error which contain the error code.

2023-06-13 06:34 UTC, aprajshekhar commented
> I request to pause the merge, @Builder annotation is still creating conflicts, working on it, will be fixed by tomorrow.
> Every other changes have been made. creating a repo feature/Error which contain the error code.
> 

If builder is creating problems, let's park it for the time being. We can come back to it later. Just create an issue for tracking purposes. Thanks!

2023-06-13 17:46 UTC, picksitquick commented
@aprajshekhar 
My apologies for the late reply but, everything now seems to be working, I do need to make unit test cases for mappers which I will update asap, for now, dao, dto and mappers with their implementations are working. Although I would request you to review the changes one last time.

Updates:
1. @Data has been replaced with @Getter and @Setter, using @Data and ignoring default functions like toString() was becoming time consuming, will keep on looking for that but for now this works fine.
2. @Builder has been added to every POJO and is now functional.
3. @Builder requires public constructor while creating objects, which was being missed by @Data annotation, hence an additional @AllArgsConstructor has also been added
4. Lastly, the root cause, spring-boot-starter was not able to process some dependency after adding all these annotation along with map_struct so had to go back to the basics, added spring-context in pom.xml which is ideally the basic spring module, resolved this error.

Not sure whether all of this combined makes it a better approach or not, please let me know if any changes are needed.
This branch can now be merged.

2023-06-14 01:24 UTC, aprajshekhar commented
Good job. Before I merge, can you confirm that the model works well with user services?

2023-06-18 14:02 UTC, merged