Updated DAO Models
gamedoora/gamedoora-model pull request #29
Opened 2023-07-10 13:06 UTC by picksitquick

@aprajshekhar please review

## Changes

  - Updated Models to mapManyToMany
  - made minor refactorings

2023-07-12 04:22 UTC, aprajshekhar requested changes
Thanks for the PR. Few queries. 

Also change `columnDefinition = "false"`  to `columnDefinition = "nullable=false"` wherever appropriate.

2023-07-12 04:22 UTC, aprajshekhar commented on src/main/java/com/gamedoora/model/dao/Skills.java
>  	Set<UserSkills> userSkills;
Shouldn't this be `Set<Users>`

2023-07-12 04:22 UTC, aprajshekhar commented on src/main/java/com/gamedoora/model/dao/Skills.java
> +	Set<Skills> skills;
Shouldn't this be `Set<Roles>`?

2023-07-12 04:22 UTC, aprajshekhar commented on src/main/java/com/gamedoora/model/dao/Sources.java
> +	Set<Sources> sources;
Shouldn't this be `Set<Skills>`?

2023-07-12 04:22 UTC, aprajshekhar commented on src/main/java/com/gamedoora/model/dao/Tenants.java
> +public class Tenants extends Audit {
Observational: Wouldn't there be a ManyToMany with Users?

2023-07-23 03:41 UTC, aprajshekhar approved these changes
LGTM. There are merge conflicts. Please have a look at them.

2023-07-23 18:44 UTC, picksitquick commented
Conflicts Resolved, we can now merge this branch.

2023-07-24 01:10 UTC, merged